{
 "title": "ISP Checker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "hosts",
    "query": {
     "query": "label_values(isp_ping_latency_ms,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "isp_ping_latency_ms{host=~\"$hosts\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Packet Loss (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "isp_packet_loss_percent{host=~\"$hosts\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "p90" ] } },
   "targets": [
    { "expr": "isp_download_speed_mbps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "p90" ] } },
   "targets": [
    { "expr": "isp_upload_speed_mbps", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Last Ping Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isp_last_ping_time{host=~\"$hosts\"} * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Last Ping Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isp_last_speed_test_time * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}